apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    app: my-web
    env: dev
    tier: api
spec:
  containers:
    - name: my-web-container
      image: antonirr/ant-test-v1:tagname
      ports:
        - containerPort: 8000
# kubectl apply -f hello-v1.yaml
