apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels:
    app: app-v1
    env: dev
    version: v1
spec:
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
        - name: app-v1-container
          image: antonirr/ant-test-v1:tagname
          ports:
            - containerPort: 8000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-v1
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-v1-service
spec:
  selector:
    app: app-v1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
# for minikube use: minikube tunnel
# kubectl apply -f ant-app-serv.yaml

# use node port for in k8n communication between pods: NodePort
