apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels:
    app: app-v1
    env: dev
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
        - name: app-v1-container
          image: antonirr/ant-test-v1:tagname
          ports:
            - containerPort: 8000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-v1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
# kubectl apply -f ant-app-dep-v1.yaml
